language: objective-c
osx_image: xcode7
podfile: MSColorPickerDemo
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=MSColorPickerDemo
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -workspace ./MSColorPickerDemo/MSColorPickerDemo.xcworkspace -scheme MSColorPickerDemo -sdk iphonesimulator9.1 ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild test -workspace ./MSColorPickerDemo/MSColorPickerDemo.xcworkspace -scheme MSColorPickerDemo -sdk iphonesimulator9.1 ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
